/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    TButton: typeof import('tdesign-vue-next')['Button']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TSpace: typeof import('tdesign-vue-next')['Space']
  }
}
